### ISSUE TITLE
Unable to run any test. 

### ISSUE THREAD

**Issue by fmeyer** [gabrihellmateus/todo-js#1]
```
fm@thrall:todo-js/app[master]# karma start
20 04 2016 16:20:47.849:WARN [karma]: No captured browser, open http://localhost:9876/
20 04 2016 16:20:47.857:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
20 04 2016 16:20:55.845:INFO [Chrome 49.0.2623 (Mac OS X 10.11.4)]: Connected on socket /#_Lb0fCXvucuhlGvoAAAA with id manual-4947
Chrome 49.0.2623 (Mac OS X 10.11.4) ERROR
  You need to include some adapter that implements __karma__.start method!


20 04 2016 16:21:04.110:WARN [Chrome 49.0.2623 (Mac OS X 10.11.4)]: Disconnected (1 times)
20 04 2016 16:21:04.546:INFO [Chrome 49.0.2623 (Mac OS X 10.11.4)]: Connected on socket /#LonRLYsggau5PDY6AAAB with id manual-7597
Chrome 49.0.2623 (Mac OS X 10.11.4) ERROR
  You need to include some adapter that implements __karma__.start method!


^C^C^C^C^C^C^C^C^C^C(node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Server.addListener (events.js:252:17)
    at Server.once (events.js:278:8)
    at Server.__dirname.Server.Server.close (net.js:1478:12)
    at /usr/local/lib/node_modules/karma/lib/server.js:345:17
    at tryCatcher (/usr/local/lib/node_modules/karma/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/karma/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/karma/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/karma/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/local/lib/node_modules/karma/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/karma/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/karma/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
^C^C^C%

```

**Comment by gabrihellmateus** [comment]
This error is because you may have run `karma start` in the wrong directory.
To tests run you need run the command from the root directory (same directory of the `karma.conf.js`).
It was my fault, I haven't explained this test flow in README. I will add this.

See the examples:

Wrong directory
------------
![screen shot 2016-04-21 at 12 25 50](https://cloud.githubusercontent.com/assets/1394578/14714674/4b4cb746-07bc-11e6-95a5-fab103858976.png) 

Correct directory
------------ 
![screen shot 2016-04-21 at 12 25 57](https://cloud.githubusercontent.com/assets/1394578/14714686/54351bf0-07bc-11e6-83f0-e9ad2a19fff7.png)
